insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZN15-50', 'Chevrolet', 'Off-road', 2, 1, 5, 19629, 1961);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('JJ07-27', 'BMW', 'Truck', 0, 1, 5, 84599, 2003);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KO02-52', 'Chevrolet', 'Utility', 3, 3, 1, 93058, 1978);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('YU31-26', 'Hyundai', 'All-wheel Drive', 4, 2, 7, 88473, 1960);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PZ07-06', 'Nissan', 'Crew Cab', 2, 0, 4, 63384, 1948);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ML79-24', 'Mercedes-Benz', 'Compact', 2, 2, 1, 81847, 1976);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GM29-46', 'Ford', 'Pickup', 3, 3, 8, 6350, 1962);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CF93-55', 'Toyota', 'Compact Pickup', 4, 2, 4, 11134, 1971);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UN98-01', 'BMW', 'Hatchback', 2, 1, 4, 73650, 2002);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AB48-72', 'Nissan', 'Plug-in Hybrid', 3, 0, 3, 90970, 1962);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BE91-81', 'Honda', 'Compact SUV', 3, 3, 1, 75292, 1942);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('MV11-93', 'Hyundai', 'Subcompact', 3, 3, 6, 79068, 2006);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('MG75-80', 'Audi', 'Minivan', 4, 1, 8, 87290, 1999);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UK42-94', 'Toyota', 'Wagon', 0, 0, 6, 49764, 1977);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('QI21-08', 'Chevrolet', 'Sport', 2, 0, 7, 22810, 1994);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KR41-61', 'Volkswagen', 'Front-wheel Drive', 1, 1, 4, 41929, 1966);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('RO99-00', 'Nissan', 'Minivan', 2, 3, 8, 66116, 1945);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZU96-38', 'Audi', 'Rear-wheel Drive', 3, 3, 7, 53440, 1958);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DJ42-05', 'Chevrolet', 'Truck', 0, 0, 1, 29333, 1980);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CL41-71', 'Chevrolet', 'Off-road', 4, 2, 4, 58384, 2002);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZB73-36', 'Mercedes-Benz', 'Eco-friendly', 1, 0, 5, 52221, 1933);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('TC97-61', 'BMW', 'Coupe', 3, 3, 4, 28701, 1948);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('EK86-37', 'Honda', 'Sedan', 3, 0, 6, 31010, 2005);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NJ46-68', 'Audi', 'Economy', 3, 2, 8, 51695, 2000);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('JK54-32', 'Mercedes-Benz', 'Extended Cab', 3, 3, 8, 62258, 1990);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UL22-97', 'Honda', 'Minivan', 1, 1, 8, 93233, 1960);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DU74-14', 'Audi', 'Rear-wheel Drive', 4, 3, 7, 11313, 2016);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('QF58-22', 'Audi', 'Convertible', 3, 2, 2, 61448, 1956);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VD10-57', 'Nissan', 'Regular Cab', 1, 3, 2, 11669, 1994);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PL75-77', 'Chevrolet', 'Convertible', 0, 0, 5, 98136, 1995);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UG81-91', 'Volkswagen', 'City', 2, 1, 2, 29016, 1941);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DZ58-55', 'Toyota', 'Retro', 0, 2, 2, 41993, 2005);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LF68-61', 'Honda', 'Eco-friendly', 2, 3, 4, 82047, 1950);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LP50-35', 'Audi', 'Front-wheel Drive', 2, 1, 7, 79349, 1977);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VX11-22', 'Volkswagen', 'Family', 0, 0, 8, 60992, 2016);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CD55-06', 'Toyota', 'Electric', 1, 1, 7, 92448, 1964);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XH33-89', 'Ford', 'Modern', 0, 0, 8, 46059, 1947);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PZ09-80', 'Mercedes-Benz', 'City', 0, 3, 3, 93088, 1956);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DO88-00', 'Audi', 'Roadster', 3, 1, 1, 72787, 1949);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AG04-81', 'Audi', 'Classic', 1, 2, 8, 92575, 1936);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KD34-48', 'Chevrolet', 'Van', 0, 2, 7, 66672, 1947);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IJ40-45', 'Audi', 'Front-wheel Drive', 3, 1, 5, 51952, 1991);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZF55-75', 'Honda', 'Convertible', 4, 1, 0, 30575, 2019);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('RM24-77', 'Toyota', 'Grand Tourer', 2, 0, 6, 88395, 1961);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GE80-99', 'Volkswagen', 'Economy', 4, 0, 8, 28209, 1963);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DE57-78', 'Nissan', 'Utility', 2, 2, 2, 14500, 1944);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SC18-92', 'BMW', 'Sport', 1, 2, 5, 99115, 2003);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DT82-57', 'Hyundai', 'Mid-size', 2, 3, 2, 9168, 1956);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FG89-13', 'Chevrolet', 'Modern', 2, 2, 3, 44757, 1954);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('EP80-14', 'Volkswagen', 'Van', 4, 3, 7, 8520, 1949);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FJ21-21', 'Mercedes-Benz', 'Compact Pickup', 0, 0, 2, 18503, 1937);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LL47-79', 'Honda', 'Subcompact', 1, 3, 8, 99464, 1989);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GO65-61', 'Hyundai', 'Rear-wheel Drive', 2, 0, 4, 56289, 1936);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VE57-00', 'Chevrolet', 'Roadster', 1, 0, 5, 97174, 2019);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DE47-69', 'BMW', 'Grand Tourer', 1, 3, 1, 25135, 2011);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WC35-91', 'Mercedes-Benz', 'Adventure', 1, 3, 8, 87985, 1985);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VK65-93', 'Toyota', 'Convertible', 2, 1, 5, 16598, 1997);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AK83-20', 'Chevrolet', 'Mid-size', 0, 1, 4, 1061, 2013);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('TL21-10', 'Toyota', 'Convertible', 2, 0, 7, 15987, 1995);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KK42-79', 'Ford', 'Pickup', 4, 0, 5, 1892, 1952);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LE93-05', 'Chevrolet', 'Coupe', 4, 2, 7, 95663, 1969);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IH75-59', 'BMW', 'Subcompact', 2, 0, 6, 13141, 1976);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZW51-25', 'Chevrolet', 'Off-road', 3, 2, 4, 63087, 1977);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XM27-00', 'Toyota', 'Crossover', 4, 1, 0, 63076, 1991);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BA23-26', 'Toyota', 'Sedan', 0, 2, 0, 63791, 1960);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LN68-95', 'BMW', 'Luxury', 0, 0, 7, 95236, 1986);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WD17-14', 'Volkswagen', 'Wagon', 1, 3, 8, 77342, 1956);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BH23-66', 'Honda', 'Hybrid', 1, 3, 1, 9231, 1980);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UR04-98', 'Hyundai', 'Compact Pickup', 2, 3, 5, 89102, 1951);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FW12-86', 'Ford', 'Electric', 0, 0, 4, 2493, 1951);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KB09-02', 'Ford', 'Regular Cab', 1, 1, 0, 83979, 1954);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('TX87-87', 'Mercedes-Benz', 'Subcompact', 4, 0, 7, 19957, 1942);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('JN85-12', 'Nissan', '4x4', 1, 1, 1, 29431, 1943);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OH17-50', 'Volkswagen', 'Retro', 3, 1, 0, 51715, 1988);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DA00-33', 'Audi', '4x4', 1, 0, 0, 76934, 1994);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FV89-03', 'Nissan', 'Subcompact', 1, 3, 2, 94, 1934);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OR80-83', 'BMW', 'Full-size', 2, 1, 1, 26538, 1935);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XR14-15', 'Volkswagen', 'Rear-wheel Drive', 2, 1, 3, 81154, 1987);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DI40-66', 'Volkswagen', 'Truck', 2, 0, 6, 91219, 2001);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('HS25-69', 'Hyundai', 'Roadster', 0, 3, 1, 22969, 1976);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NC24-63', 'Hyundai', 'Classic', 1, 1, 8, 53008, 1980);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GQ94-01', 'BMW', 'Utility', 3, 3, 2, 43022, 1939);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GM81-55', 'Hyundai', 'Retro', 1, 1, 7, 43698, 1941);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PY41-39', 'Hyundai', 'Supermini', 1, 1, 3, 56076, 1955);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DH38-36', 'Chevrolet', 'Regular Cab', 4, 3, 5, 9074, 1982);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KQ07-40', 'Chevrolet', 'Compact', 1, 2, 8, 26756, 2008);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XP60-00', 'Mercedes-Benz', 'Regular Cab', 3, 2, 5, 48570, 2005);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IT54-30', 'Toyota', 'Compact', 0, 2, 7, 84844, 1989);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XG60-53', 'Hyundai', 'Extended Cab', 1, 2, 3, 21328, 2003);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IB21-33', 'Volkswagen', '4x4', 1, 2, 1, 94584, 1964);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SA62-00', 'Mercedes-Benz', 'Performance', 3, 0, 8, 62071, 1946);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('YZ03-12', 'Mercedes-Benz', 'Mid-size', 4, 0, 2, 67604, 2004);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SL79-89', 'Honda', 'Coupe', 1, 0, 7, 3663, 1953);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XU35-38', 'Honda', 'All-wheel Drive', 3, 3, 8, 32974, 2000);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PZ93-61', 'BMW', 'Rear-wheel Drive', 0, 3, 0, 77869, 1934);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VV32-69', 'Honda', 'Premium', 4, 3, 7, 83552, 1966);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('JH96-14', 'BMW', 'Premium', 2, 3, 1, 58578, 1985);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ER02-54', 'Hyundai', 'Adventure', 1, 1, 2, 61657, 1983);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OO33-41', 'Chevrolet', 'Truck', 0, 2, 3, 54799, 1934);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KK08-49', 'Honda', 'Supermini', 0, 3, 2, 91214, 2007);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UK23-80', 'Audi', 'Subcompact', 1, 2, 5, 87810, 1986);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('EE66-03', 'BMW', 'Plug-in Hybrid', 0, 2, 8, 48021, 1962);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LV06-87', 'Toyota', 'Economy', 4, 3, 3, 83513, 1994);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PO54-71', 'Nissan', 'Luxury', 0, 2, 0, 50719, 1971);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SW58-34', 'Toyota', 'Regular Cab', 1, 0, 8, 34282, 2020);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('EW82-54', 'Ford', 'Hot Hatch', 3, 3, 4, 61714, 1998);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VZ97-68', 'Honda', '4x4', 2, 3, 4, 36198, 2000);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OF80-69', 'Audi', 'Off-road', 1, 1, 1, 33768, 2009);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('YX95-85', 'Chevrolet', 'City', 0, 2, 8, 17219, 1940);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AX53-08', 'Chevrolet', 'Compact SUV', 4, 0, 0, 87610, 1934);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VN53-79', 'Volkswagen', 'Coupe', 2, 1, 8, 29778, 1992);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WW38-16', 'BMW', 'All-wheel Drive', 2, 1, 7, 92001, 1956);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IQ13-01', 'Audi', 'Economy', 0, 0, 2, 37990, 1941);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CN95-03', 'Honda', 'Subcompact', 1, 3, 1, 71223, 1956);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('MF71-16', 'Audi', 'Crew Cab', 2, 3, 2, 24537, 1950);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('MA79-48', 'Hyundai', 'Limousine', 2, 3, 6, 38088, 1986);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GB36-72', 'Nissan', 'Subcompact', 1, 3, 6, 4928, 2017);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IV95-61', 'Chevrolet', 'Hot Hatch', 3, 0, 8, 30338, 1962);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DH69-50', 'BMW', 'Crew Cab', 1, 3, 2, 51475, 1937);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LG47-48', 'Mercedes-Benz', 'Sedan', 1, 3, 0, 33301, 1935);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VV96-13', 'Mercedes-Benz', 'Muscle', 0, 2, 5, 96361, 1991);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CH89-19', 'Audi', 'Subcompact', 1, 1, 0, 13928, 2018);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KU40-26', 'Ford', 'Pickup', 2, 0, 0, 22847, 1948);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('MM85-10', 'BMW', 'Limousine', 3, 1, 3, 59884, 1995);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('HC56-04', 'Mercedes-Benz', 'Rear-wheel Drive', 1, 0, 0, 81859, 1982);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KH18-62', 'Honda', 'Muscle', 2, 3, 5, 49010, 1938);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CT79-07', 'Honda', 'Compact Pickup', 2, 2, 3, 45298, 1948);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WL67-70', 'Mercedes-Benz', 'Wagon', 1, 0, 0, 44710, 1981);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZW31-13', 'Toyota', 'Mid-size', 2, 2, 2, 81027, 1935);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IF20-57', 'Nissan', 'Roadster', 2, 3, 0, 6644, 2020);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XZ72-02', 'Chevrolet', 'Off-road', 2, 3, 6, 35065, 1935);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SB61-66', 'Toyota', 'Utility', 4, 1, 2, 44879, 1962);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GV26-87', 'Toyota', 'Sedan', 2, 0, 7, 79813, 1996);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('YS42-34', 'Mercedes-Benz', 'Compact Pickup', 2, 0, 0, 32831, 1976);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SZ66-07', 'Toyota', 'Rear-wheel Drive', 2, 1, 3, 89260, 2008);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('HD56-80', 'Honda', 'Pickup', 2, 2, 3, 65642, 1952);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('JE97-20', 'Hyundai', 'Convertible', 2, 1, 6, 37752, 1980);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('XT97-43', 'Chevrolet', 'Full-size', 1, 0, 7, 20680, 1998);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OF00-45', 'Audi', '4x4', 0, 0, 5, 69009, 2006);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('QA79-73', 'Chevrolet', 'Performance', 0, 1, 1, 578, 2003);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NG27-00', 'Audi', 'Full-size', 1, 2, 2, 47587, 1979);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WR94-87', 'Volkswagen', 'Supermini', 2, 3, 1, 73091, 1994);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DU85-45', 'Audi', 'Hatchback', 0, 3, 7, 70821, 1997);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FF06-35', 'Nissan', 'Coupe', 2, 2, 2, 73542, 1972);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IR50-59', 'Chevrolet', 'Plug-in Hybrid', 3, 3, 6, 36372, 1983);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NF13-65', 'Audi', 'Rear-wheel Drive', 1, 3, 3, 79205, 1976);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AC94-85', 'Toyota', 'Hatchback', 4, 0, 3, 3890, 1982);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AP60-44', 'BMW', 'Plug-in Hybrid', 3, 3, 1, 34168, 1997);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GC98-54', 'Hyundai', 'Economy', 3, 2, 5, 12913, 1960);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KM11-22', 'Mercedes-Benz', 'Minivan', 4, 3, 6, 80013, 1942);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZP22-19', 'Mercedes-Benz', 'Regular Cab', 3, 2, 3, 86887, 2020);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('YB88-58', 'Audi', 'Hatchback', 2, 1, 1, 2365, 1962);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NL64-21', 'Volkswagen', 'Racing', 3, 2, 5, 22652, 1947);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FU27-65', 'Chevrolet', 'Luxury', 2, 2, 2, 16794, 2004);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DH74-20', 'Ford', 'Truck', 3, 0, 4, 66065, 1934);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DC03-67', 'Audi', 'All-wheel Drive', 0, 0, 7, 63534, 1976);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZU70-23', 'BMW', 'Racing', 4, 0, 8, 62614, 1970);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OW16-03', 'Volkswagen', 'Roadster', 1, 2, 5, 88819, 2003);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OC38-54', 'BMW', 'Compact', 3, 2, 2, 68529, 1977);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('UM73-86', 'Ford', 'Truck', 1, 2, 4, 71137, 2017);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VJ30-47', 'Chevrolet', 'Hatchback', 4, 1, 8, 81564, 1940);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WB77-70', 'BMW', 'Van', 2, 1, 7, 15989, 1946);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NV93-02', 'Mercedes-Benz', 'Supermini', 2, 0, 5, 6972, 1957);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AA79-73', 'BMW', 'Compact', 1, 1, 2, 38476, 1934);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NY16-95', 'Honda', 'Sedan', 1, 2, 4, 99671, 1968);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IC74-28', 'Nissan', 'Limousine', 4, 2, 7, 53035, 1958);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZX35-72', 'Ford', 'Sport', 0, 1, 8, 49276, 1998);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LP37-98', 'Hyundai', 'Modern', 1, 3, 4, 23294, 1952);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DZ19-10', 'Chevrolet', 'Pickup', 0, 0, 4, 24118, 1935);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('YD25-25', 'Chevrolet', 'Premium', 3, 3, 5, 86037, 1981);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IG93-78', 'BMW', 'Performance', 2, 1, 3, 1332, 2014);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('FA29-17', 'Hyundai', 'Muscle', 0, 0, 1, 35341, 2013);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('OW50-86', 'Audi', 'Coupe', 0, 3, 2, 5020, 2012);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('TD19-94', 'Volkswagen', 'Roadster', 4, 1, 0, 1237, 2017);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BR40-22', 'Chevrolet', 'Adventure', 1, 3, 5, 18580, 2019);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GR70-12', 'BMW', 'City', 3, 1, 6, 32127, 2011);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SG88-45', 'Mercedes-Benz', 'Hybrid', 3, 2, 4, 40662, 1978);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GG94-58', 'Ford', 'Compact', 3, 0, 6, 26289, 1964);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('WN54-01', 'Toyota', 'Compact SUV', 1, 0, 0, 12140, 1945);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KT96-01', 'Audi', 'Racing', 0, 1, 6, 73517, 2007);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('DS64-16', 'Ford', 'Compact SUV', 3, 0, 8, 31193, 2018);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZV03-56', 'Ford', 'Extended Cab', 3, 0, 2, 92569, 1961);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('CL16-94', 'Mercedes-Benz', 'Economy', 4, 1, 3, 8644, 1973);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('KZ14-97', 'Ford', 'Convertible', 0, 0, 0, 46690, 1984);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('GB27-06', 'Audi', 'Compact Pickup', 4, 1, 4, 38449, 1938);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('IA27-05', 'Chevrolet', 'Compact', 1, 1, 8, 16588, 2001);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('ZI70-47', 'Volkswagen', 'Full-size', 3, 3, 1, 65491, 2008);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AG88-34', 'Honda', 'Family', 4, 0, 8, 94011, 2020);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('NE99-04', 'Chevrolet', 'Crossover', 1, 2, 5, 94441, 1938);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('LO36-70', 'Chevrolet', 'Performance', 2, 1, 8, 75329, 2005);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BQ91-21', 'Nissan', 'Electric', 2, 2, 5, 88144, 1946);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PC01-40', 'Hyundai', 'Van', 3, 0, 6, 97523, 1975);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BU49-91', 'Chevrolet', 'Supermini', 1, 0, 3, 20689, 1997);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SK86-24', 'Hyundai', 'Utility', 1, 2, 1, 799, 2016);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('VK09-67', 'Ford', 'Supermini', 0, 0, 3, 26746, 1995);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('PY31-83', 'Hyundai', 'Classic', 1, 0, 3, 28732, 1947);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('BN62-38', 'Volkswagen', 'Grand Tourer', 4, 1, 5, 31319, 1971);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('SY98-20', 'Volkswagen', 'Crew Cab', 0, 1, 1, 91492, 1986);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('TB98-53', 'Nissan', 'Adventure', 2, 2, 5, 79845, 1966);
insert into public.vehiculo (patente, marca, modelo, car_type, motor_type, n_asientos, km_recorridos, fabrication_year) values ('AR21-28', 'Nissan', 'Eco-friendly', 0, 2, 5, 48426, 1980);

insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 159, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 172, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 25, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 134, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 158, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 159, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 109, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 105, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 13, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 29, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 164, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 184, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 153, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 128, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 160, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 200, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 134, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 62, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 128, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 112, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 147, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 5, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 18, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 73, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 147, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 101, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 163, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 198, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 129, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 58, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 77, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 192, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 14, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 185, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 127, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 39, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 3, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 41, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 102, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 95, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 150, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 182, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 116, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 199, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 151, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 37, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 100, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 180, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 127, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 97, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 143, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 197, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 4, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 15, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 120, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 142, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 151, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 58, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 7, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 6, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 190, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 70, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 124, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 11, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 51, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 151, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 123, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 13, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 158, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 177, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 150, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 158, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 173, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 120, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 87, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 73, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 90, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 29, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 181, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 48, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 139, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 133, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 15, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 11, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 105, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 39, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 118, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 162, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 169, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 116, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, true, 134, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 158, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 105, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 173, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, true, 89, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 194, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 46, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (false, false, 26, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 146, 0);
insert into public.boleta (pagado, retirado, patente_vehiculo, costo_total) values (true, false, 198, 0);


insert into public.bono (amount, marca, usado, vehiculo_id) values (248022, 'BMW', true, 43);
insert into public.bono (amount, marca, usado, vehiculo_id) values (738378, 'Chevrolet', true, 83);
insert into public.bono (amount, marca, usado, vehiculo_id) values (683182, 'Mercedes-Benz', true, 15);
insert into public.bono (amount, marca, usado, vehiculo_id) values (601859, 'Hyundai', true, 63);
insert into public.bono (amount, marca, usado, vehiculo_id) values (344782, 'Mercedes-Benz', true, 50);
insert into public.bono (amount, marca, usado, vehiculo_id) values (176238, 'Volkswagen', false, 43);
insert into public.bono (amount, marca, usado, vehiculo_id) values (134705, 'Nissan', true, 71);
insert into public.bono (amount, marca, usado, vehiculo_id) values (283700, 'Volkswagen', false, 19);
insert into public.bono (amount, marca, usado, vehiculo_id) values (511456, 'Toyota', false, 59);
insert into public.bono (amount, marca, usado, vehiculo_id) values (309423, 'Hyundai', false, 65);
insert into public.bono (amount, marca, usado, vehiculo_id) values (436088, 'Audi', true, 37);
insert into public.bono (amount, marca, usado, vehiculo_id) values (472537, 'Hyundai', true, 35);
insert into public.bono (amount, marca, usado, vehiculo_id) values (266373, 'Mercedes-Benz', false, 9);
insert into public.bono (amount, marca, usado, vehiculo_id) values (490470, 'BMW', true, 5);
insert into public.bono (amount, marca, usado, vehiculo_id) values (233946, 'Hyundai', true, 74);
insert into public.bono (amount, marca, usado, vehiculo_id) values (423344, 'Honda', true, 27);
insert into public.bono (amount, marca, usado, vehiculo_id) values (247702, 'Nissan', false, 71);
insert into public.bono (amount, marca, usado, vehiculo_id) values (411963, 'BMW', false, 94);
insert into public.bono (amount, marca, usado, vehiculo_id) values (359266, 'Honda', true, 37);
insert into public.bono (amount, marca, usado, vehiculo_id) values (523248, 'Hyundai', false, 55);
insert into public.bono (amount, marca, usado, vehiculo_id) values (575580, 'Toyota', true, 2);
insert into public.bono (amount, marca, usado, vehiculo_id) values (554741, 'Audi', false, 75);
insert into public.bono (amount, marca, usado, vehiculo_id) values (614768, 'Toyota', true, 75);
insert into public.bono (amount, marca, usado, vehiculo_id) values (279103, 'Mercedes-Benz', true, 2);
insert into public.bono (amount, marca, usado, vehiculo_id) values (630106, 'BMW', true, 48);
insert into public.bono (amount, marca, usado, vehiculo_id) values (330547, 'Hyundai', false, 88);
insert into public.bono (amount, marca, usado, vehiculo_id) values (636587, 'Hyundai', false, 83);
insert into public.bono (amount, marca, usado, vehiculo_id) values (502548, 'Nissan', false, 47);
insert into public.bono (amount, marca, usado, vehiculo_id) values (409258, 'Mercedes-Benz', false, 9);
insert into public.bono (amount, marca, usado, vehiculo_id) values (659600, 'Chevrolet', false, 88);
insert into public.bono (amount, marca, usado, vehiculo_id) values (770567, 'Hyundai', false, 23);
insert into public.bono (amount, marca, usado, vehiculo_id) values (666671, 'Honda', false, 72);
insert into public.bono (amount, marca, usado, vehiculo_id) values (612770, 'Nissan', false, 96);
insert into public.bono (amount, marca, usado, vehiculo_id) values (656088, 'Ford', true, 32);
insert into public.bono (amount, marca, usado, vehiculo_id) values (664664, 'Ford', false, 20);
insert into public.bono (amount, marca, usado, vehiculo_id) values (578569, 'BMW', true, 29);
insert into public.bono (amount, marca, usado, vehiculo_id) values (768070, 'Mercedes-Benz', true, 85);
insert into public.bono (amount, marca, usado, vehiculo_id) values (277631, 'Chevrolet', true, 47);
insert into public.bono (amount, marca, usado, vehiculo_id) values (494228, 'Mercedes-Benz', true, 4);
insert into public.bono (amount, marca, usado, vehiculo_id) values (270178, 'Hyundai', true, 22);
insert into public.bono (amount, marca, usado, vehiculo_id) values (266610, 'Hyundai', false, 21);
insert into public.bono (amount, marca, usado, vehiculo_id) values (369772, 'Honda', true, 61);
insert into public.bono (amount, marca, usado, vehiculo_id) values (684395, 'Toyota', false, 58);
insert into public.bono (amount, marca, usado, vehiculo_id) values (366901, 'Chevrolet', true, 11);
insert into public.bono (amount, marca, usado, vehiculo_id) values (756845, 'Hyundai', true, 34);
insert into public.bono (amount, marca, usado, vehiculo_id) values (454121, 'Chevrolet', true, 35);
insert into public.bono (amount, marca, usado, vehiculo_id) values (538451, 'BMW', false, 59);
insert into public.bono (amount, marca, usado, vehiculo_id) values (678662, 'Nissan', true, 52);
insert into public.bono (amount, marca, usado, vehiculo_id) values (769819, 'Honda', true, 46);
insert into public.bono (amount, marca, usado, vehiculo_id) values (138718, 'Honda', true, 54);
insert into public.bono (amount, marca, usado, vehiculo_id) values (294204, 'Chevrolet', false, 73);
insert into public.bono (amount, marca, usado, vehiculo_id) values (747705, 'Volkswagen', true, 20);
insert into public.bono (amount, marca, usado, vehiculo_id) values (526170, 'Mercedes-Benz', true, 66);
insert into public.bono (amount, marca, usado, vehiculo_id) values (551167, 'Mercedes-Benz', true, 28);
insert into public.bono (amount, marca, usado, vehiculo_id) values (793512, 'Audi', true, 37);
insert into public.bono (amount, marca, usado, vehiculo_id) values (599287, 'Toyota', true, 46);
insert into public.bono (amount, marca, usado, vehiculo_id) values (367372, 'Chevrolet', false, 67);
insert into public.bono (amount, marca, usado, vehiculo_id) values (519200, 'Chevrolet', false, 57);
insert into public.bono (amount, marca, usado, vehiculo_id) values (297882, 'Chevrolet', false, 22);
insert into public.bono (amount, marca, usado, vehiculo_id) values (544527, 'Toyota', false, 89);
insert into public.bono (amount, marca, usado, vehiculo_id) values (226086, 'Ford', false, 18);
insert into public.bono (amount, marca, usado, vehiculo_id) values (680245, 'Ford', true, 70);
insert into public.bono (amount, marca, usado, vehiculo_id) values (340866, 'Honda', true, 41);
insert into public.bono (amount, marca, usado, vehiculo_id) values (540417, 'Honda', true, 50);
insert into public.bono (amount, marca, usado, vehiculo_id) values (246334, 'Honda', true, 90);
insert into public.bono (amount, marca, usado, vehiculo_id) values (409432, 'Mercedes-Benz', false, 11);
insert into public.bono (amount, marca, usado, vehiculo_id) values (723741, 'Volkswagen', true, 9);
insert into public.bono (amount, marca, usado, vehiculo_id) values (285796, 'Toyota', false, 65);
insert into public.bono (amount, marca, usado, vehiculo_id) values (776593, 'Honda', false, 18);
insert into public.bono (amount, marca, usado, vehiculo_id) values (654540, 'Ford', false, 83);
insert into public.bono (amount, marca, usado, vehiculo_id) values (650637, 'BMW', false, 68);
insert into public.bono (amount, marca, usado, vehiculo_id) values (305219, 'Hyundai', true, 88);
insert into public.bono (amount, marca, usado, vehiculo_id) values (463388, 'Ford', false, 99);
insert into public.bono (amount, marca, usado, vehiculo_id) values (622612, 'Hyundai', true, 55);
insert into public.bono (amount, marca, usado, vehiculo_id) values (556734, 'Honda', false, 20);
insert into public.bono (amount, marca, usado, vehiculo_id) values (235452, 'Chevrolet', true, 14);
insert into public.bono (amount, marca, usado, vehiculo_id) values (421325, 'Volkswagen', true, 59);
insert into public.bono (amount, marca, usado, vehiculo_id) values (787708, 'Nissan', false, 13);
insert into public.bono (amount, marca, usado, vehiculo_id) values (698282, 'Honda', false, 18);
insert into public.bono (amount, marca, usado, vehiculo_id) values (121562, 'Nissan', true, 73);
insert into public.bono (amount, marca, usado, vehiculo_id) values (560204, 'Audi', true, 99);
insert into public.bono (amount, marca, usado, vehiculo_id) values (441218, 'Nissan', false, 7);
insert into public.bono (amount, marca, usado, vehiculo_id) values (655383, 'Hyundai', true, 90);
insert into public.bono (amount, marca, usado, vehiculo_id) values (361330, 'Chevrolet', true, 8);
insert into public.bono (amount, marca, usado, vehiculo_id) values (518261, 'Chevrolet', false, 41);
insert into public.bono (amount, marca, usado, vehiculo_id) values (569237, 'Honda', true, 66);
insert into public.bono (amount, marca, usado, vehiculo_id) values (366373, 'Ford', false, 47);
insert into public.bono (amount, marca, usado, vehiculo_id) values (497436, 'Volkswagen', true, 68);
insert into public.bono (amount, marca, usado, vehiculo_id) values (699037, 'Ford', true, 72);
insert into public.bono (amount, marca, usado, vehiculo_id) values (393553, 'Nissan', false, 6);
insert into public.bono (amount, marca, usado, vehiculo_id) values (167305, 'BMW', true, 21);
insert into public.bono (amount, marca, usado, vehiculo_id) values (133991, 'BMW', false, 49);
insert into public.bono (amount, marca, usado, vehiculo_id) values (569600, 'Mercedes-Benz', false, 25);
insert into public.bono (amount, marca, usado, vehiculo_id) values (405631, 'Ford', true, 17);
insert into public.bono (amount, marca, usado, vehiculo_id) values (633129, 'Chevrolet', true, 58);
insert into public.bono (amount, marca, usado, vehiculo_id) values (577322, 'Honda', false, 32);
insert into public.bono (amount, marca, usado, vehiculo_id) values (462737, 'BMW', true, 9);
insert into public.bono (amount, marca, usado, vehiculo_id) values (782983, 'Volkswagen', false, 20);
insert into public.bono (amount, marca, usado, vehiculo_id) values (540309, 'Volkswagen', true, 91);
insert into public.bono (amount, marca, usado, vehiculo_id) values (428011, 'Mercedes-Benz', false, 63);
